
import React from 'react';
import { Facility } from './types';

export const TRANSLATIONS = {
  en: {
    appName: 'Aayu',
    tagline: 'Quick health check (triage). Not a medical diagnosis.',
    startCheck: 'Start New Check',
    startVoiceCheck: 'Start Voice Triage',
    emergencyCheck: 'Emergency? Get help now',
    patientProfile: 'Patient Profile',
    symptoms: 'Symptoms',
    consent: 'I understand this is not a medical diagnosis and is for guidance only.',
    age: 'Age',
    sex: 'Sex',
    weeksPregnant: 'Weeks Pregnant',
    describeSymptoms: 'Describe symptoms + severity',
    symptomDuration: 'How long have you had these symptoms?',
    durationPlaceholder: 'e.g. 3',
    hours: 'Hours',
    days: 'Days',
    weeks: 'Weeks',
    mandatoryFields: 'Age and consent are required',
    weeksMandatory: 'Weeks pregnant is required',
    loading: 'Analyzing your symptoms...',
    next: 'Continue',
    back: 'Back',
    whyAsk: 'Why we ask this',
    results: 'Triage Results',
    notDiagnosis: 'Not a diagnosis',
    doNow: 'Do now',
    dangerSigns: 'Danger signs',
    doctorSummary: 'Doctor summary',
    copySummary: 'Copy Summary',
    shareWhatsapp: 'Share via WhatsApp',
    nearbyFacilities: 'Nearby Facilities',
    startOver: 'Return Home',
    editAnswers: 'Edit Answers',
    somethingWrong: 'This seems wrong',
    emergencyTitle: 'Emergency Help',
    emergencyDangerSigns: 'Dangerous Symptoms:',
    callHelp: 'Call Local Help',
    findHospital: 'Find Nearest Hospital',
    feedbackTitle: 'Give Feedback',
    feedbackPlaceholder: 'What seems wrong?',
    visitedDoctor: 'I visited a doctor',
    doctorSaid: 'What did the doctor say?',
    submit: 'Submit',
    cancel: 'Cancel',
    success: 'Thank you for your feedback!',
    recentHistory: 'Recent History',
    noHistory: 'No recent checks found.',
    howItWorks: 'How it works',
    howStep1: 'Tell us about the patient.',
    howStep2: 'Describe symptoms (voice or text).',
    howStep3: 'Follow the guidance and share with a doctor.',
    listening: 'Listening...',
    voiceError: 'Speech not recognized. Please try again or type.',
    useCurrentLocation: 'Use my current location',
    youAreHere: 'You are here',
    voiceTriageTitle: 'Live Voice Assistant',
    voiceTriageDesc: 'Talk naturally to the assistant. They will ask follow-up questions to help triage your symptoms.',
    connecting: 'Connecting to Assistant...',
    endSession: 'End Session',
    voiceInstruction: 'Please describe how you are feeling.',
    legalDisclaimer: '* AI-generated. Not medical advice. Errors possible.'
  },
  hi: {
    appName: 'आयु',
    tagline: 'त्वरित स्वास्थ्य जांच। यह चिकित्सा निदान नहीं है।',
    startCheck: 'नई जाँच शुरू करें',
    startVoiceCheck: 'वॉयस ट्राइएज शुरू करें',
    emergencyCheck: 'आपातकालीन? अभी मदद लें',
    patientProfile: 'रोगी की जानकारी',
    symptoms: 'लक्षण',
    consent: 'मैं समझता हूँ कि यह चिकित्सा निदान नहीं है और केवल मार्गदर्शन के लिए है।',
    age: 'आयु',
    sex: 'लिंग',
    weeksPregnant: 'गर्भावस्था के सप्ताह',
    describeSymptoms: 'लक्षणों + गंभीरता का वर्णन करें',
    symptomDuration: 'आपको ये लक्षण कितने समय से हैं?',
    durationPlaceholder: 'जैसे 3',
    hours: 'घंटे',
    days: 'दिन',
    weeks: 'सप्ताह',
    mandatoryFields: 'आयु और सहमति आवश्यक है',
    weeksMandatory: 'गर्भावस्था के सप्ताह आवश्यक हैं',
    loading: 'आपके लक्षणों का विश्लेषण किया जा रहा है...',
    next: 'आगे बढ़ें',
    back: 'पीछे',
    whyAsk: 'हम यह क्यों पूछते हैं',
    results: 'परिणाम',
    notDiagnosis: 'निदान नहीं है',
    doNow: 'अभी क्या करें',
    dangerSigns: 'खतरे के संकेत',
    doctorSummary: 'डॉक्टर के लिए सार',
    copySummary: 'सार कॉपी करें',
    shareWhatsapp: 'व्हाट्सएप पर साझा करें',
    nearbyFacilities: 'नज़दीकी स्वास्थ्य केंद्र',
    startOver: 'मुख्य स्क्रीन पर लौटें',
    editAnswers: 'उत्तर बदलें',
    somethingWrong: 'यह गलत लग रहा है',
    emergencyTitle: 'आपातकालीन मदद',
    emergencyDangerSigns: 'खतरनाक लक्षण:',
    callHelp: 'स्थानीय सहायता को कॉल करें',
    findHospital: 'नज़दीकी अस्पताल खोजें',
    feedbackTitle: 'प्रतिक्रिया दें',
    feedbackPlaceholder: 'क्या गलत लग रहा है?',
    visitedDoctor: 'मैंने डॉक्टर को दिखाया',
    doctorSaid: 'डॉक्टर ने क्या कहा?',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    success: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    recentHistory: 'हालिया इतिहास',
    noHistory: 'कोई हालिया जांच नहीं मिली।',
    howItWorks: 'यह कैसे काम करता है',
    howStep1: 'रोगी के बारे में जानकारी दें।',
    howStep2: 'लक्षण बताएं (आवाज या टेक्स्ट)।',
    howStep3: 'मार्गदर्शन का पालन करें और डॉक्टर के साथ साझा करें।',
    listening: 'सुन रहे हैं...',
    voiceError: 'आवाज पहचानी नहीं जा सकी। फिर से कोशिश करें या टाइप करें।',
    useCurrentLocation: 'मेरी वर्तमान स्थिति का उपयोग करें',
    youAreHere: 'आप यहाँ हैं',
    voiceTriageTitle: 'लाइव वॉयस असिस्टेंट',
    voiceTriageDesc: 'असिस्टेंट से स्वाभाविक रूप से बात करें। वे आपके लक्षणों को समझने के लिए आपसे कुछ सवाल पूछेंगे।',
    connecting: 'असिस्टेंट से जुड़ रहे हैं...',
    endSession: 'सत्र समाप्त करें',
    voiceInstruction: 'कृपया बताएं कि आप कैसा महसूस कर रहे हैं।',
    legalDisclaimer: '* AI-जनित। चिकित्सा सलाह नहीं। त्रुटियां संभव।'
  }
};

export const MOCK_FACILITIES: Facility[] = [
  {
    name: "Government Primary Health Centre (PHC)",
    type: "PHC",
    hours: "24/7",
    phone: "102",
    distance: "1.2 km",
    lat: 28.6200,
    lng: 77.2100
  },
  {
    name: "City Civil Hospital",
    type: "Public Hospital",
    hours: "24/7",
    phone: "108",
    distance: "4.5 km",
    lat: 28.6000,
    lng: 77.2300
  },
  {
    name: "Lifeline Clinic",
    type: "Private Clinic",
    hours: "9:00 AM - 9:00 PM",
    phone: "+91 98765 43210",
    distance: "0.8 km",
    lat: 28.6150,
    lng: 77.2000
  }
];

export const RISK_FACTORS = [
  { id: 'diabetes', labelEn: 'Diabetes', labelHi: 'मधुमेह' },
  { id: 'bp', labelEn: 'High Blood Pressure', labelHi: 'उच्च रक्तचाप' },
  { id: 'asthma', labelEn: 'Asthma / COPD', labelHi: 'अस्थमा / सीओपीडी' },
  { id: 'tb', labelEn: 'TB history', labelHi: 'टीबी का इतिहास' },
  { id: 'immune', labelEn: 'Immunocompromised', labelHi: 'कमजोर प्रतिरक्षा प्रणाली' }
];

export const PATIENT_TYPES = [
  { id: 'Adult', labelEn: 'Adult', labelHi: 'वयस्क' },
  { id: 'Child', labelEn: 'Child', labelHi: 'बच्चा' },
  { id: 'Pregnant', labelEn: 'Pregnant', labelHi: 'गर्भवती' },
  { id: 'Elderly', labelEn: 'Elderly', labelHi: 'बुजुर्ग' }
];
